version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
      # environment:
      # - MONGO_INITDB_ROOT_USERNAME=dev
      # - MONGO_INITDB_ROOT_PASSWORD=pass
      # MONGO_INITDB_ROOT_USERNAME: dev
      # MONGO_INITDB_ROOT_PASSWORD: pass
    env_file:
      - './env/mongo.env'
    # networks:
    #   - goal-net
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
    env_file:
      - './env/backend.env'
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  data:
  logs:
